---
# Source: ui/templates/config.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: react-ui-config
  labels:
    app: react-ui
    env: dev
data:
  config.yaml: |
    database:
      ip: 10.20.30.20
      name: ui-dev
    logfile: /app/var/log.txt
    timeout: 10s
---
# Source: ui/templates/configmap-xml.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: react-ui-config-xml
  labels:
    app: react-ui
    env: dev
data:
  app.xml: |
  
  
    <receivers>
      <topic>
        <options type="receiver">
          <option name="ordered_delivery" order="deny">
            <deny>0</deny>
          </option>
        </options>
      </topic>
    </receivers>
---
# Source: ui/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels:
    app: react-ui
    env: dev
spec:
    type: ClusterIP
    selector:
        component: client
    ports:
     -   port: 3000
         targetPort: 3000
---
# Source: ui/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-ui-dep
  labels:
    app: react-ui
    env: dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-ui
  template:
    metadata:
      labels:
        app: react-ui
        env: dev
    spec:
      containers:
        - name: react-ui
          image: 300974211/frontend
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 0.2
              memory: 500Mi
            requests:
              cpu: 0.2
              memory: 500Mi
