apiVersion: v1
kind: Service
metadata:
  name: ui-service
  labels: 
  {{- include "ui.labels" . | nindent 4 }}
spec:
    type: ClusterIP
    selector:
        component: client
    ports:
     -   port: 3000
         targetPort: 3000