app:
  replicas: 1
  env: prod
  container:
    image: 300974211/frontend
  computerc:
    limits:
      memory: 500Mi
      cpu: 0.2 
    requests:
      memory: 500Mi
      cpu: 0.2

hpa: # is not required for dev env
  enabled: true
  maxReplicas: 10
  minReplicas: 4
  cpuuti: 50

config:
  name: config.yaml
  data: 
    timeout: 2s
    logfile: /app/var/log.txt
    database:
      ip: 120.220.230.20
      name: ui-prod